### ISSUE TITLE
Getting error when running docker compose up from master...

### ISSUE THREAD

**Issue by chetanpan** [jajm/koha-docker#10]
master-intranet-1       | exec /usr/local/bin/docker-entrypoint.sh: no such file or directory
master-opac-1           | exec /usr/local/bin/docker-entrypoint.sh: no such file or directory

I am running win 11 pro with Docker version 24.0.6, build ed223bc

Please help...

**Comment by musama9** [comment]
I have the same problem

**Comment by chetanpan** [comment]
@musama9 Any luck?

**Comment by fbifido** [comment]
Step 10/21 : ADD --chown=koha:koha https://api.github.com/repos/Koha-Community/Koha/git/refs/heads/master version.json                                                                                          
ADD failed: failed to GET https://api.github.com/repos/Koha-Community/Koha/git/refs/heads/master with status 404 Not Found: {"message":"Not Found","documentation_url":"https://docs.github.com/rest/git/refs#ge
t-all-references-in-a-namespace"}                                                                                                                                                                               
ERROR: Service 'intranet' failed to build : Build failed

**Comment by zdub0is** [comment]
Change all master references to `main` in `dockerfile` and it will work. Koha changed their branch name from master to main sometime since the last commit to this repository. To handle issue #13, you will have to download [the Koha sql schema](https://github.com/Koha-Community/Koha/blob/main/installer/data/mysql/kohastructure.sql) and import it into the mariadb docker container then run: `mariadb -u koha -p koha < {path to imported kohastructure}` so it makes the tables.

**Comment by chetanpan** [comment]
> Change all master references to `main` in `dockerfile` and it will work. Koha changed their branch name from master to main sometime since the last commit to this repository. To handle issue #13, you will have to download [the Koha sql schema](https://github.com/Koha-Community/Koha/blob/main/installer/data/mysql/kohastructure.sql) and import it into the mariadb docker container then run: `mariadb -u koha -p koha < {path to imported kohastructure}` so it makes the tables.

Thanks, this woked for me!
